# Generated by Django 3.2.5 on 2021-08-10 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210809_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, help_text='Unique ID for this particular book accross whole library', primary_key=True, serialize=False),
        ),
    ]
